config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :resturants

  resources :menu_items

  root :to => redirect('/resturants')

end

app/models/resturant.rb
class Resturant < ActiveRecord::Base
	  mount_uploader :image, ImageUploader

end

app/controllers/resturants_controller.rb
class ResturantsController < ApplicationController
  before_action :set_resturant, only: [:show, :edit, :update, :destroy]
 before_filter :authenticate_user!, :except =>[:show,:index]
  #before_filter :authenticate_user!
  # GET /resturants
  # GET /resturants.json
  def index
    @resturants = Resturant.all
  end

  # GET /resturants/1
  # GET /resturants/1.json
  def show
        @menu_items = MenuItem.all

  end

  # GET /resturants/new
  def new
    @resturant = Resturant.new
  end

  # GET /resturants/1/edit
  def edit
  end

  # POST /resturants
  # POST /resturants.json
  def create
    @resturant = Resturant.new(resturant_params)

    respond_to do |format|
      if @resturant.save
        format.html { redirect_to @resturant, notice: 'Resturant was successfully created.' }
        format.json { render :show, status: :created, location: @resturant }
      else
        format.html { render :new }
        format.json { render json: @resturant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resturants/1
  # PATCH/PUT /resturants/1.json
  def update
    respond_to do |format|
      if @resturant.update(resturant_params)
        format.html { redirect_to @resturant, notice: 'Resturant was successfully updated.' }
        format.json { render :show, status: :ok, location: @resturant }
      else
        format.html { render :edit }
        format.json { render json: @resturant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resturants/1
  # DELETE /resturants/1.json
  def destroy
    @menu_items = MenuItem.all
    @menu_items.each do |menu_item|
      if menu_item.resturant_id ==@resturant.id
    menu_item.destroy
      end
    end

    @resturant.destroy

    respond_to do |format|
      format.html { redirect_to resturants_url, notice: 'Resturant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resturant
      @resturant = Resturant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resturant_params
      params.require(:resturant).permit(:name, :discription, :location, :image)
    end
end

app/helpers/resturants_helper.rb
module ResturantsHelper
end

app/views/resturants/_form.html.erb
<%= form_for(@resturant) do |f| %>
  <% if @resturant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resturant.errors.count, "error") %> prohibited this resturant from being saved:</h2>

      <ul>
      <% @resturant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name ,:class => "form-control"%>
  </div>
  <div class="field">
    <%= f.label :discription %><br>
    <%= f.text_field :discription ,:class => "form-control"%>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location ,:class => "form-control"%>
  </div>
  <div class="field">
     <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/resturants/edit.html.erb
<div class="container">

<h1>Editing Resturant</h1>

<%= render 'form' %>

<%= link_to 'Show', @resturant %> |
<%= link_to 'Back', resturants_path %>
 <div id="user_nav" style="float:right ">
            <% if user_signed_in? %>
              Signed in as <%= current_user.email %>. 
              <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
            <% end %>
  </div>
</div>

app/views/resturants/index.html.erb
<div class="container" style="padding:5px">
   <%= button_to "Menu Items", "/menu_items",:style =>"float:right", 
        :class => "btn btn-info", :method => :get %>
  <h1>Resturants</h1>
 
  <table class="table table-striped">
    <thead>
      <tr class="info">
        <th>Name</th>
        <th>Description</th>
        <th>Location</th>
        <th></th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @resturants.each do |resturant| %>
        <tr>
          <td><%= resturant.name %></td>
          <td><%= resturant.discription %></td>
          <td><%= resturant.location %></td>
          <td><%= link_to 'Show', resturant %></td>
          <td><%= link_to 'Edit', edit_resturant_path(resturant) %></td>
          <td><%= link_to 'Delete', resturant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </br>
  <%= button_to "New Resturant", new_resturant_path,:style =>"margin-left:5px", 
        :class => "btn btn-success", :method => :get %>
 <div id="user_nav" style="float:right ">
            <% if user_signed_in? %>
              Signed in as <%= current_user.email %>. 
              <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
            <% end %>
  </div>
</div>

app/views/resturants/new.html.erb
<div class="container">

<h1>New resturant</h1>

<%= render 'form' %>

<%= link_to 'Back', resturants_path %>
 <div id="user_nav" style="float:right ">
            <% if user_signed_in? %>
              Signed in as <%= current_user.email %>. 
              <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
            <% end %>
  </div>
</div>

app/views/resturants/show.html.erb
<div class="container">
<h1>Resturant</h1>

<h3 id="notice"><%= notice %></h3>
<table class="table table-hover">
<tr class="info">
  <td>Name:</td>
  <td><%= @resturant.name %></td>
</tr>

<tr class="active">
  <td>Discription:</td>
  <td><%= @resturant.discription %></td>
</tr>
<tr class="info">
  <td>Location:</td>
  <td><%= @resturant.location %></td>
</tr>
<tr class="active">
  <td>Image:</td>
  <td> <%= image_tag(@resturant.image_url, :height =>100) if @resturant.image.present?%></td>
</tr>

</table>

<%i =0%>
<table class="table table-hover">
<% @menu_items.each do |menu_item| %>
     <% if menu_item.resturant_id ==@resturant.id%>
     <%i+=1%>
   <%end%>
<%end%>
<%if i>0%>
<h1>Menu</h1>

<%end%>
<% @menu_items.each do |menu_item| %>
     <% if menu_item.resturant_id ==@resturant.id%>

<tr class="success">
  <th >Name:</th>
  <td><%= menu_item.name%> &nbsp &nbsp &nbsp<%= image_tag(menu_item.picture_url, :height =>50) if menu_item.picture.present?%></td>
</tr>
<tr class="active">
  <th>Price:</th>
  <td><%= menu_item.price %></td>
</tr>
<tr class="active">
  <th>Desription:</th>
  <td><%= menu_item.desription %></td>
</tr>


<%end%>
<%end%>
</table>



<%= link_to 'Edit', edit_resturant_path(@resturant),:style =>"margin-left:5px" %> |
<%= link_to 'Back', resturants_path %>
 <div id="user_nav" style="float:right ">
            <% if user_signed_in? %>
              Signed in as <%= current_user.email %>. 
              <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
            <% end %>
  </div>
</div>