config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :resturants

  resources :menu_items

  root :to => redirect('/resturants')

end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  belongs_to :resturant , dependent: :destroy
  mount_uploader :picture, PictureUploader
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except =>[:show,:index]

  # GET /menu_items
  # GET /menu_items.json
  def index
    @menu_items = MenuItem.all
  end

  # GET /menu_items/1
  # GET /menu_items/1.json
  def show
  end

  # GET /menu_items/new
  def new
    @menu_item = MenuItem.new
  end

  # GET /menu_items/1/edit
  def edit
  end

  # POST /menu_items
  # POST /menu_items.json
  def create
    @menu_item = MenuItem.new(menu_item_params)

    respond_to do |format|
      if @menu_item.save
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully created.' }
        format.json { render :show, status: :created, location: @menu_item }
      else
        format.html { render :new }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_items/1
  # PATCH/PUT /menu_items/1.json
  def update
    respond_to do |format|
      if @menu_item.update(menu_item_params)
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu_item }
      else
        format.html { render :edit }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1
  # DELETE /menu_items/1.json
  def destroy
    @menu_item.destroy
    respond_to do |format|
      format.html { redirect_to menu_items_url, notice: 'Menu item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_item
      @menu_item = MenuItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_item_params
      params.require(:menu_item).permit(:name, :price, :desription, :resturant_id, :picture)
    end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/menu_items/_form.html.erb
<%= form_for @menu_item , :html => {:multipart => true} do |f| %>
  <% if @menu_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
      <% @menu_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name ,:class => "form-control"%>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :desription %><br>
    <%= f.text_field :desription ,:class => "form-control"%>
  </div>
  <div class="field">
     <%= f.label :resturant_id %><br>
     <%= f.collection_select :resturant_id, Resturant.order(:name),:id,:name %>

  </div>
  <div class="field">
    <%= f.file_field :picture %>

  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/menu_items/edit.html.erb
<div class="container">

<h1>Editing Menu Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu_item %> |
<%= link_to 'Back', menu_items_path %>
    <div id="user_nav" style="float:right ">
        <% if user_signed_in? %>
          Signed in as <%= current_user.email %>. Not you?
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
        <% end %>
    </div>
</div>

app/views/menu_items/index.html.erb
<div class="container"style="padding:5px">
   <%= button_to "Resturants", "/resturants",:style =>"float:right", 
        :class => "btn btn-info", :method => :get %>
 
  <h1 >Menu Items</h1>

  <table class="table table-striped">
    <thead>
      <tr class="info">
        <th>Name</th>
        <th>Price</th>
        <th>Desription</th>
        <th>Resturant</th>
        <th></th>
        <th></th>
        <th></th>

      </tr>
    </thead>

    <tbody>
      <% @menu_items.each do |menu_item| %>
        <tr>
          <td><%= menu_item.name %></td>
          <td><%= menu_item.price %></td>
          <td><%= menu_item.desription %></td>
          <td><%= menu_item.resturant.name %></td>
          <td><%= link_to 'Show', menu_item %></td>
          <td><%= link_to 'Edit', edit_menu_item_path(menu_item) %></td>
          <td><%= link_to 'Delete', menu_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         </tr>
      <% end %>
    </tbody>
  </table>
  <%= button_to "New Menu Item", new_menu_item_path, 
      :class => "btn btn-success", :method => :get %>
    <div id="user_nav" style="float:right ">
        <% if user_signed_in? %>
          Signed in as <%= current_user.email %>. Not you?
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
        <% end %>
    </div>
</div>

app/views/menu_items/new.html.erb
<div class="container">

	<h1>New Menu Item</h1>

	<%= render 'form' %>

	<%= link_to 'Back', menu_items_path %>
	    <div id="user_nav" style="float:right ">
        <% if user_signed_in? %>
          Signed in as <%= current_user.email %>. Not you?
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
        <% end %>
    </div>
</div>

app/views/menu_items/show.html.erb
<div class="container">

<h1>Menu Item</h1>
<h3 id="notice"><%= notice %></h3>
<table class="table table-hover">

<tr class="info">
  <th >Name:</th>
  <td><%= @menu_item.name %></td>
</tr>

<tr class="active">
  <th>Price:</th>
  <td><%= @menu_item.price %></td>
</tr>

<tr class="info">
  <th>Desription:</th>
  <td><%= @menu_item.desription %></td>
</p>

<tr class="active">
  <th>Resturant:</th>
  <td><%= @menu_item.resturant.name %></td>
</tr>
<tr class="info">
  <th>Image:</th>

 <td> <%= image_tag(@menu_item.picture_url, :height =>100) if @menu_item.picture.present?%></td>
</tr>
</table>
<%= link_to 'Edit', edit_menu_item_path(@menu_item) ,:style =>"margin-left:5px"%> |
<%= link_to 'Back', menu_items_path %>
	<div id="user_nav" style="float:right">
            <% if user_signed_in? %>
              Signed in as <%= current_user.email %>. Not you?
              <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
            <% end %>
          </div>
</div>